include:
  - html5up/docker-compose.yml
  - nginx/docker-compose.yml
  - django-soft-1766014025/docker-compose.yml
  - ecommerce-fastapi-stripe/docker-compose.yml
  - flask-black-dashboard/docker-compose.yml
  - priv-rocket-ecommerce-main/docker-compose.yml
