services:
  nginx:
    image: nginx:alpine-slim
    ports:
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
