services:
  rocket-django:
    restart: always
    build: .
    image: sgttabasco/rocket-django:part-2
    expose:
      - "5005"
    environment:
      - STRIPE_SECRET_KEY=
      - STRIPE_PUBLISHABLE_KEY=
